#!/usr/bin/env bash
# Install a single OpenTrApp shield as a standalone CLI (modular distribution).
#
#   scripts/install-shield.sh <shield> [--bindir DIR]
#   e.g. scripts/install-shield.sh openagent-skills
#        → installs a `skills` command that runs the scanner/CDR with no GUI.
#
# This is the local/dev installer: it reads distribution.yml (the single source)
# and drops a thin CLI wrapper on PATH that shells to the shield's own tools.
# The production installer (curl | sh from a release) additionally fetches the
# shield's GHCR image by digest; the wrapper + tool surface are identical.
#
# Demonstrates the Pillar-B promise: a tech-savvy user installs ONE lean shield
# and drives it via CLI — no GUI, no other shields, no five-container AppImage.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DIST="$REPO_ROOT/distribution.yml"
BINDIR="${HOME}/.local/bin"

SHIELD="${1:-}"
shift || true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --bindir) BINDIR="$2"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$SHIELD" ]]; then
  echo "Usage: install-shield.sh <shield> [--bindir DIR]"
  echo ""
  echo "Available shields:"
  python3 -c "import yaml,sys; d=yaml.safe_load(open('$DIST')); [print(f'  {n:24s} {s[\"summary\"]}') for n,s in d['shields'].items() if s.get('standalone')]"
  exit 1
fi

PY=$(command -v python3) || { echo "Python 3 required" >&2; exit 1; }

# Resolve the shield from distribution.yml — the single source of truth.
read -r CLI DIRS < <("$PY" - "$DIST" "$SHIELD" <<'PYEOF'
import sys, yaml
dist = yaml.safe_load(open(sys.argv[1]))
shield = sys.argv[2]
s = dist.get("shields", {}).get(shield)
if not s:
    sys.stderr.write(f"Unknown shield '{shield}'. Known: {', '.join(dist['shields'])}\n"); sys.exit(2)
if not s.get("standalone"):
    sys.stderr.write(f"Shield '{shield}' is not standalone-installable.\n"); sys.exit(2)
print(s["cli"], ",".join(s["dirs"]))
PYEOF
)

PRIMARY_DIR="${DIRS%%,*}"   # the shield's main directory
TOOL_ROOT="$REPO_ROOT/$PRIMARY_DIR"

mkdir -p "$BINDIR"
WRAPPER="$BINDIR/$CLI"

cat > "$WRAPPER" <<WRAP
#!/usr/bin/env bash
# OpenTrApp shield CLI wrapper for '$SHIELD' (generated by install-shield.sh).
# Runs the shield's own tooling against its local install — no GUI required.
set -euo pipefail
TOOL_ROOT="$TOOL_ROOT"
if [[ -f "\$TOOL_ROOT/Makefile" && \$# -gt 0 ]]; then
  # First arg maps to a Makefile target when one exists; remaining args pass through.
  target="\$1"; shift
  if make -C "\$TOOL_ROOT" -n "\$target" >/dev/null 2>&1; then
    exec make -C "\$TOOL_ROOT" "\$target" "\$@"
  fi
  # Fall back to a tools/ script named skill-<target>.sh.
  if [[ -f "\$TOOL_ROOT/tools/skill-\$target.sh" ]]; then
    exec bash "\$TOOL_ROOT/tools/skill-\$target.sh" "\$@"
  fi
  echo "Unknown '$CLI' command: \$target" >&2
  echo "Try: make -C \$TOOL_ROOT help" >&2
  exit 2
fi
exec make -C "\$TOOL_ROOT" help
WRAP
chmod +x "$WRAPPER"

echo "Installed '$CLI' → $WRAPPER"
echo "  (driving $PRIMARY_DIR — no GUI, no other shields)"
case ":$PATH:" in
  *":$BINDIR:"*) : ;;
  *) echo "  Note: add $BINDIR to your PATH to use '$CLI' directly." ;;
esac
